name: eky_pos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0
  flutter: 3.32.6

dependencies:
  flutter:
    sdk: flutter
  esc_pos_utils_plus: ^2.0.4
  flutter_bloc: ^9.1.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  mobile_scanner: ^6.0.10
  open_filex: ^4.7.0
  percent_indicator: ^4.2.5
  pdf: ^3.11.3
  permission_handler: ^12.0.1
  print_bluetooth_thermal: ^1.1.6
  shared_preferences: ^2.5.3
  sqflite: ^2.4.1
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  bloc: ^9.0.0
  freezed_annotation: ^3.1.0
  uuid: ^4.5.1
  talker: ^4.9.2
  talker_bloc_logger: ^4.9.2
  qr: ^3.0.2
  qr_flutter: ^4.1.0
  responsive_builder: ^0.7.1
  http: ^1.4.0
  provider: ^6.1.5
  go_router: ^16.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.5.0
  freezed: ^3.1.0
  build_runner: ^2.5.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/products/
    - assets/icons/

flutter_launcher_icons:
  android: true
  image_path_android: "assets/icons/ekycashier_radiusborder.png"
  min_sdk_android: 21
  ios: true
  remove_alpha_ios: true
  image_path_ios: "assets/icons/ekycashier_blue.png"
  image_path_ios_dark_transparent: "assets/icons/ekycashier_dark.png"
  desaturate_tinted_to_grayscale_ios: true

