version: 2.1

orbs:
  flutter: circleci/flutter@3.0.0
  android: circleci/android@3.1.0

executors:
  macos-executor:
    macos:
      xcode: 16.3
    resource_class: macos.m1.medium.gen1
  
  android-executor:
    docker:
      - image: cimg/android:2023.09.1
    resource_class: medium

jobs:
  build_ios:
    executor: macos-executor
    steps:
      - checkout  

      - flutter/install_sdk_and_pub:
          channel: stable
          version: 3.32.6

      # - flutter/install_ios_pod
          
      - run:
          name: Install dependencies
          command: flutter pub get
          
      - run:
          name: Install iOS platform tools
          command: |
            flutter config --enable-ios
            flutter precache --ios
            
      - run:
          name: Build iOS
          command: flutter build ipa --release --no-codesign

  build_android:
    executor: android-executor
    steps:
      - checkout
      
      - flutter/install_sdk_and_pub:
          channel: stable
          version: 3.32.6

      - run:
          name: Upgrade AGP version
          command: |
            source $BASH_ENV
            # Check if settings.gradle exists and update AGP version
            if [ -f "android/settings.gradle" ]; then
              sed -i 's/id "com.android.application" version "[0-9.]*"/id "com.android.application" version "8.2.1"/' android/settings.gradle
              echo "Updated AGP version in settings.gradle"
            fi
      
      - run:
          name: Accept Android licenses
          command: yes | flutter doctor --android-licenses || true
          
      - run:
          name: Install dependencies
          command: flutter pub get
          
      - run:
          name: Build Android
          command: flutter build apk --release --target-platform=android-arm64

workflows:
  build-workflow:  # This should be a workflow name, not "jobs"
    jobs:          # "jobs" should be under the workflow name
      - build_ios
      - build_android